# Site settings
title: mascott or Scott Maslar
email: scott.maslar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Eventually this is where I will regale you with stories of my harrowing
  adventures, but until then you can check out my resume.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mascott.github.io" # the base hostname & protocol for your site
twitter_username: @scottmaslar
github_username:  mascott

# Build settings
markdown: kramdown
